# -*- coding: utf-8 -*-

from odoo import models, fields, api
from datetime import datetime

class VoiceConversation(models.Model):
    _name = 'voice.conversation'
    _description = 'Voice Conversation History'
    _order = 'create_date desc'
    _rec_name = 'user_input'

    user_id = fields.Many2one(
        'res.users',
        string='User',
        required=True,
        default=lambda self: self.env.user,
        index=True,
    )
    
    user_input = fields.Text(
        string='User Input (Transcribed)',
        required=True,
        help='The transcribed text from user\'s voice input',
    )
    
    ai_response = fields.Text(
        string='AI Response',
        help='The response generated by the AI processor',
    )
    
    final_response = fields.Text(
        string='Final Response',
        help='The final response text that was converted to speech',
    )
    
    audio_input_id = fields.Many2one(
        'ir.attachment',
        string='Input Audio',
        help='Audio file containing the user\'s voice input',
    )
    
    conversation_date = fields.Datetime(
        string='Date',
        default=fields.Datetime.now,
        required=True,
        index=True,
    )
    
    processing_time = fields.Float(
        string='Processing Time (seconds)',
        help='Time taken to process the entire request',
    )
    
    error_message = fields.Text(
        string='Error Message',
        help='Error message if processing failed',
    )
    
    state = fields.Selection(
        [
            ('draft', 'Draft'),
            ('processing', 'Processing'),
            ('completed', 'Completed'),
            ('error', 'Error'),
        ],
        string='State',
        default='draft',
        required=True,
    )

    def name_get(self):
        """Custom name display"""
        result = []
        for record in self:
            name = f"{record.user_input[:50]}..." if len(record.user_input) > 50 else record.user_input
            result.append((record.id, name))
        return result

