{
    "name": "Dojang Communications",
    "version": "saas~19.2.1.0.0",
    "summary": "Automated SMS/email for check-in parent alerts, session reminders, and instructor messaging",
    "author": "Dojang",
    "category": "Dojo",
    "license": "LGPL-3",
    "depends": [
        "dojo_core",
        "sms_twilio",
        "sms",
        "mail",
        "mass_mailing",
        "mass_mailing_sms",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/mail_template_checkin.xml",
        "data/mail_template_reminder.xml",
        "data/ir_cron.xml",
        "views/dojo_send_message_wizard_view.xml",
        "views/dojo_member_view_inherit.xml",
        "views/dojo_class_session_view_inherit.xml",
    ],
    "installable": True,
    "auto_install": False,
}
