services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data-19-2:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: .
    image: odoo-saas-19-2:latest
    depends_on:
      - db
    ports:
      - "8069:8069" # Change the port if needed.
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./enterprise:/mnt/enterprise-addons
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    restart: unless-stopped

volumes:
  odoo-db-data-19-2:
  odoo-web-data: