{
    "name": "Dojang Subscriptions",
    "summary": "Membership plans and subscriptions",
    "version": "saas~19.2.4.3.0",
    "category": "Dojo",
    "license": "LGPL-3",
    "author": "Dojang",
    "depends": ["dojo_core", "account"],
    "data": [
        "security/ir.model.access.csv",
        "security/dojo_subscriptions_security.xml",
        "data/membership_product.xml",
        "data/mail_template_dunning.xml",
        "data/mail_template_expiry_reminder.xml",
        "data/mail_template_expiry_reminder_sms.xml",
        "data/ir_cron.xml",
        "views/dojo_subscription_views.xml",
        "views/dojo_program_enrollment_views.xml",
    ],
    "post_init_hook": "populate_program_enrollments",
    "application": True,
    "auto_install": True,
    "installable": True,
}
