{
    "name": "Dojang Migration",
    "summary": "SparkMembership → Odoo CSV migration tool (admin only)",
    "version": "saas~19.2.1.0.0",
    "category": "Dojo",
    "license": "LGPL-3",
    "author": "Dojang",
    "depends": [
        "dojo_core",
        "dojo_subscriptions",
    ],
    "data": [
        "security/security_groups.xml",
        "security/ir.model.access.csv",
        "views/migration_log_views.xml",
        "views/import_programs_wizard.xml",
        "views/import_belt_rank_defs_wizard.xml",
        "views/import_odoo_csv_wizard.xml",
        "views/import_member_stripes_wizard.xml",
        "views/import_members_wizard.xml",
        "views/import_subscriptions_wizard.xml",
        "views/import_ranks_wizard.xml",
        "views/import_attendance_wizard.xml",
        "views/menu.xml",
    ],
    "application": True,
    "installable": True,
}
