from . import dojo_member
from . import dojo_member_subscription
from . import dojo_subscription_plan
from . import dojo_program_inherit
from . import dojo_account_move
from . import dojo_class_template_inherit
from . import dojo_class_enrollment_inherit
from . import dojo_member_weekly_counter
from . import dojo_program_enrollment
