{
    "name": "Dojang Base",
    "summary": "Core Dojang models and security",
    "version": "saas~19.2.1.0.0",
    "category": "Services",
    "license": "LGPL-3",
    "author": "Dojang",
    "depends": ["base", "mail", "portal", "hr"],
    "data": [
        "security/dojo_security.xml",
        "security/ir.model.access.csv",
        "views/dojo_household_views.xml",
        "views/dojo_member_views.xml",
        "views/dojo_instructor_profile_views.xml",
        "views/dojo_martial_art_style_views.xml",
    ],
    "application": False,
    "installable": True,
    "post_init_hook": "post_init_hook",
}
