{
    "name": "Dojang CRM — Lead to Member Pipeline",
    "version": "19.0.2.0.0",
    "summary": "CRM stages, automations, lead scoring, trial booking, AI integration, and convert-to-member flow",
    "author": "Dojang",
    "category": "Martial Arts",
    "license": "LGPL-3",
    "depends": [
        "crm",
        "website",
        "dojo_members",
        "dojo_communications",
        "dojo_subscriptions",
        "dojo_classes",
        "dojo_sign",
        "sms",
        "mail",
        "base_automation",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/crm_tag.xml",
        "data/crm_stage.xml",
        "data/mail_template_crm.xml",
        "data/base_automation.xml",
        "data/ir_cron.xml",
        "data/ai_intent_schema_crm.xml",
        "views/crm_menu_inherit.xml",
        "views/trial_booking_templates.xml",
        "views/dojo_book_trial_wizard_view.xml",
        "views/dojo_convert_lead_wizard_view.xml",
        "views/crm_lead_view_inherit.xml",
        "views/dojo_member_view_crm_inherit.xml",
        "views/crm_dashboard.xml",
        "views/dojo_class_session_view_inherit.xml",
    ],
    "installable": True,
    "auto_install": False,
}
