{
    "name": "Dojang Automation",
    "version": "saas~19.2.1.1.0",
    "summary": "Spark-Membership-style automation builder for Dojang workflows",
    "author": "Dojo",
    "category": "Hidden",
    "depends": [
        "dojo_core",
        "automation_oca",
        "dojo_communications",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/automation_groups.xml",
        "data/sms_action_template.xml",
        "data/trigger_templates.xml",
        "data/hide_oca_app.xml",
        "data/mail_sms_templates.xml",
        "views/automation_views_inherit.xml",
        "views/automation_menus.xml",
        "views/automation_builder_views.xml",
        "views/dojo_member_tags_inherit.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "dojo_automation/static/src/xml/automation_stat_panel.xml",
            "dojo_automation/static/src/js/automation_stat_panel.js",
            "dojo_automation/static/src/css/automation.scss",
            "dojo_automation/static/src/builder/builder.xml",
            "dojo_automation/static/src/builder/builder.js",
            "dojo_automation/static/src/builder/builder.scss",
        ],
    },
    "installable": True,
    "auto_install": False,
    "post_init_hook": "post_init_hook",
    "license": "LGPL-3",
}
