{
    "name": "Dojang CRM — Lead to Member Pipeline",
    "version": "saas~19.2.2.0.0",
    "summary": "CRM stages, automations, lead scoring, trial booking, AI integration, and convert-to-member flow",
    "author": "Dojang",
    "category": "Dojo",
    "license": "LGPL-3",
    "depends": [
        "dojo_core",
        "crm",
        "website",
        "dojo_communications",
        "dojo_subscriptions",
        "dojo_sign",
        "dojo_stripe",
        "sms",
        "mail",
        "base_automation",
        "ai_assistant",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/dojo_crm_security.xml",
        "data/crm_tag.xml",
        "data/crm_stage.xml",
        "data/mail_template_crm.xml",
        "data/base_automation.xml",
        "data/ir_cron.xml",
        "data/ai_intent_schema_crm.xml",
        "views/crm_menu_inherit.xml",
        "views/trial_booking_templates.xml",
        "views/dojo_book_trial_wizard_view.xml",
        "views/dojo_convert_lead_wizard_view.xml",
        "views/crm_lead_view_inherit.xml",
        "views/dojo_member_view_crm_inherit.xml",
        "views/crm_dashboard.xml",
        "views/dojo_class_session_view_inherit.xml",
    ],

    "installable": True,
    "auto_install": False,
    "assets": {
        "web.assets_backend": [
            "dojo_crm/static/src/xml/crm_convert_stripe_payment.xml",
            "dojo_crm/static/src/js/crm_convert_stripe_payment.js",
        ],
    },
}
